chore: refactor redux
realponto-project/stock-rp-front pull request #137
Opened 2021-02-04 15:04 UTC by jessiLeandro

## Contexto
A lógica e configuração não foram alterados, apenas a estruturação e os nomes.

## Issues linkadas
- [ ] Resolves #131 

## Como testar?

1. Baixar a branch `refactor/redux`.
2. Startar a aplicação. o back-end deve estar na branch `changeMiddleware` ou posteriores.
3. Tester os fluxos onde usa-se o redux, login/updates.

2021-02-05 01:08 UTC, alexandrejuk requested changes

2021-02-05 01:08 UTC, alexandrejuk commented on src/store/Reducers/auth.js
> +      return auth
deveria ser assim essa alteração no state
```suggestion
       return ({
          ...state,
          ...action.payload,
        })
```

2021-02-05 01:08 UTC, alexandrejuk commented on src/services/Suprimentos/entrada.js
>  import axios from "axios";
Deveriamos ter um arquivo com esse conteudo aqui dentro de helps, chamado request.js


```js
import axios from 'axios'
import { store } from '../../store/configureStore';
const storeObject = store.getState();

const baseURL = 'http://localhost:3003/api'

const axiosInstance = axios.create({ baseURL })

axiosInstance.interceptors.request.use(config => ({
  ...config,
  headers: {
    ...config.headers,
    token: storeObject.auth.token,
    username: storeObject.auth.username
  }
}))

export default axiosInstance
````

E nesses arquivos de serviço vc chama a instancia do axios no lugar de axios voce usaria axiosInstance.post('url', payload).then().cath

2021-02-05 14:53 UTC, jessiLeandro commented on src/services/Suprimentos/entrada.js
>  import axios from "axios";
foi feito um pt para a esta altaração

2021-02-09 11:36 UTC, novarealponto approved these changes

2021-02-09 11:51 UTC, guilhermestain approved these changes

2021-02-09 17:44 UTC, merged