User/get by
realponto-project/stock-rp-front pull request #138
Opened 2021-02-04 19:58 UTC by jessiLeandro

## Contexto
Neste foi criado a request `user/getById` e implementada no fluxo de atuializar usuário.

## Checklist
- [ ] Criar request.
- [ ] Implementar nova va request no fluxo de atualização.

## Issues linkadas
- [ ] Resolves #127 
- [ ] Resolves #52 

## Notas de deploy

Há alterações no back-end que foram feitas na branch `user/getById`.

## Como testar?

1. Baixar abransh `user/getById` , no front e no back.
2. Startar a aplicação.
3. Testar o fluxo de gerenciamento e atualização de usuário.

2021-02-05 01:16 UTC, alexandrejuk requested changes

2021-02-05 01:16 UTC, alexandrejuk commented on src/utils/userSpec.js
> +  console.log(value);
remove o console.log

2021-02-05 01:16 UTC, alexandrejuk commented on src/pages/User/EditUser/index.js
> +const mapStateToProps = ({ userReducer }) => ({
O usuario não pode vir do redux tem que vim do servilo de getByid do backend teremos que remover da store no futuro mas para esse caso temos que tirar daqui

2021-02-05 01:16 UTC, alexandrejuk commented on src/pages/User/EditUser/index.js
> +    getUserById(userReducer.id).then(({ data }) => {
esse id devemos pegar da rota e não da store
match.params.id

2021-02-05 01:16 UTC, alexandrejuk commented on src/services/usuario.js
> +  return response
temos que usar o try/catch com async await e não um then para essa promise e temos que usar o interceptor que comentei no PR de redux

2021-02-05 12:10 UTC, guilhermestain commented on src/utils/userSpec.js
> +    id: pathOr('', ['id']),
colocar em ordem alfabética

2021-02-05 14:04 UTC, jessiLeandro commented on src/pages/User/EditUser/index.js
> +const mapStateToProps = ({ userReducer }) => ({
userReducer possui apenas o id do usuário, que é inicado ao clicar em editar user na página de gerenciamento

2021-02-05 14:05 UTC, jessiLeandro commented on src/services/usuario.js
> +  return response
resolvido em outro pr

2021-02-05 16:50 UTC, guilhermestain commented on src/pages/Suprimentos/Edit.Fornecedor/EditFornecedorContainer/index.js
> +    rua: this.props.providerReducer.street,
colocar em ordem alfabética

2021-02-05 17:09 UTC, guilhermestain commented on src/pages/Suprimentos/Edit.Fornecedor/EditFornecedorContainer/index.js
> +    cep: this.props.providerReducer.zipCode,
colocar em ordem alfabética

2021-02-05 17:10 UTC, guilhermestain commented on src/pages/Technician/EditTechnician/index.js
>        carList={carList}
colocar em ordem alfabética

2021-02-05 18:33 UTC, jessiLeandro commented on src/pages/Suprimentos/Edit.Fornecedor/EditFornecedorContainer/index.js
> +    rua: this.props.providerReducer.street,
não foi feito o refactor dessa página

2021-02-09 11:55 UTC, guilhermestain approved these changes

2021-02-09 18:44 UTC, novarealponto approved these changes

2021-02-09 18:46 UTC, merged