Technician/get by
realponto-project/stock-rp-front pull request #142
Opened 2021-02-05 18:30 UTC by jessiLeandro

## Contexto
Neste foi criado a request `technician/getById` e implementada no fluxo de atuializar técnico.

## Checklist
- [ ] Criar request.
- [ ] Implementar nova va request no fluxo de atualização.

## Issues linkadas
- [ ] Resolves #126 

## Como testar?

1. Baixar abransh `technicain/getById` , no front e no back.
2. Startar a aplicação.
3. Testar o fluxo de gerenciamento e atualização de técnico.

2021-02-09 17:01 UTC, guilhermestain commented on src/pages/Suprimentos/Edit.Fornecedor/EditFornecedorContainer/index.js
> +    bairro: this.props.providerReducer.neighborhood,
colocar em ordem alfabética

2021-02-09 23:48 UTC, novarealponto requested changes

2021-02-09 23:48 UTC, novarealponto commented on src/pages/Technician/EditTechnician/index.js
> +const EditTechnician = ({ history }) => {
Aqui, vc usar o `match` pra pegar o id da rota não  dessa forma, `match.params.id`

2021-02-09 23:48 UTC, novarealponto commented on src/pages/Technician/EditTechnician/index.js
> +      )(window)
não usar dessa forma pegar o id igual mencionei na parte de cima

2021-02-09 23:48 UTC, novarealponto commented on src/pages/Technician/index.js
> +    <Route path="/logged/technician/edit" component={EditTechnician} />
para usar o id lá na tela de detalhes você precisa passar o id aqui, dessa forma fica disponível no `match.params.id`
```suggestion
    <Route path="/logged/technician/edit/:id" component={EditTechnician} />
```

2021-02-09 23:48 UTC, novarealponto commented on src/services/tecnico.js
> +  }
não precisa disso por que temos o interceptor do axios

2021-02-09 23:48 UTC, novarealponto commented on src/services/tecnico.js
> +  await axios.get(`${BACKEND_URL}/api/technician/getById`, { headers: headers, params: { id } }).then(
aqui usamos a intancia que criamos no arquivo do request e usamos aqui só importar e usar
```suggestion
  await axiosInstance.get(`${BACKEND_URL}/api/technician/getById`, { headers: headers, params: { id } })
```

2021-02-09 23:48 UTC, novarealponto commented on src/services/tecnico.js
> +  return response
aqui usamos o try/catch sem usar esse `then` depois da request

2021-02-10 13:10 UTC, alexandrejuk approved these changes

2021-02-10 18:10 UTC, guilhermestain approved these changes

2021-02-10 20:04 UTC, merged