Get by id/product
realponto-project/stock-rp-front pull request #143
Opened 2021-02-05 20:05 UTC by guilhermestain

## Contexto
Neste foi criado a request `getById/product` e implementada no fluxo de atualizar produto.

## Checklist
- [ ] Criar request.
- [ ] Implementar nova va request no fluxo de atualização.

## Issues linkadas
- [ ] Resolves #130 

## Notas de deploy

Há alterações no back-end que foram feitas na branch `getById/Products`.

## Como testar?

1. Baixar abransh `getById/product` , no front e no back.
2. Startar a aplicação.
3. Testar o fluxo de gerenciamento e atualização de produto.

2021-02-08 11:59 UTC, jessiLeandro commented on src/utils/productSpec.js
>    modulo: pathOr(false, ['modulo']),
ordem alfbética

2021-02-08 11:59 UTC, jessiLeandro commented on src/utils/productSpec.js
> +  modulo: pathOr(false, ['modulo']),
ordem alfbética

2021-02-08 11:59 UTC, jessiLeandro commented on src/pages/Product/EditProduct/index.js
> +      await updateProduto(buildProduct({ ...productReducer, ...formData, id }))
você não vai mais usar o redux para atualizar o produto, você deve excluir o productReducer da aplicação.

2021-02-09 11:36 UTC, novarealponto requested changes
tem mais mudanças do que de product id

2021-02-09 14:36 UTC, jessiLeandro commented on src/pages/Product/EditProduct/index.js
> +  getProductById,
ordem

2021-02-09 14:36 UTC, jessiLeandro commented on src/store/Actions/product.js
> +}
Você não vai mais usar o redux para setar os dados do produto

2021-02-09 14:36 UTC, jessiLeandro commented on src/store/Actions/typeActions.js
>      PRODUTO: 'INICIAL_STATE_REDIRECT_PRODUTO',
Você não precisa de um tipo de ação de editar produto pois não usará mais o redux para isso

2021-02-09 14:36 UTC, jessiLeandro commented on src/store/Reducers/index.js
> +import productReducer from './product'
Não usará esse reducer na aplicação

2021-02-09 14:36 UTC, jessiLeandro commented on src/store/Reducers/product.js
> +export default productReducer
Não usará

2021-02-09 23:53 UTC, novarealponto submitted a review, later dismissed

2021-02-09 23:53 UTC, novarealponto commented on src/pages/Product/EditProduct/index.js
> +    )(window)
mesmo caso do pr anterior
https://github.com/realponto-project/stock-rp-front/pull/142#pullrequestreview-587121573

2021-02-09 23:53 UTC, novarealponto commented on src/pages/Product/index.js
> +    <Route path='/logged/product/edit' component={EditProduct} />
passar o id igual comentei no pr anterior
https://github.com/realponto-project/stock-rp-front/pull/142#pullrequestreview-587121573

2021-02-09 23:53 UTC, novarealponto commented on src/services/produto.js
> +    })
aqui o uso do axiosInstance está certo menos a construção do restante da função, jeito correto
```suggestion
   try { 
        const response = await axiosInstance.get('/product/getByIdProducts', { params: { id } })
       return response 
   }
   catch (error) {
      /* tratar o error de qualquer jeito que você quiser*/
   }
```

2021-02-11 10:12 UTC, alexandrejuk approved these changes

2021-02-11 17:16 UTC, jessiLeandro approved these changes

2021-02-11 17:18 UTC, merged