Refactor/supply product
realponto-project/stock-rp-front pull request #149
Opened 2021-02-09 13:02 UTC by jessiLeandro

## Contexto
Foi feito o refatoramneto da página de cadastro de produto em supimentos, seguindo  o mesmo padrão das demais páginas até o momento

## Checklist
- [ ] Container.
- [ ] Storybook.
- [ ] Page.

## Issues linkadas
- [ ] Resolves #148 

## Screenshots

![image](https://user-images.githubusercontent.com/50411657/107366917-72a96780-6abd-11eb-83fe-b9ab6adb4391.png)

![image](https://user-images.githubusercontent.com/50411657/107366941-7a690c00-6abd-11eb-982b-8f8fe03d27fc.png)

![image](https://user-images.githubusercontent.com/50411657/107366964-7fc65680-6abd-11eb-8697-17d867de5020.png)

![image](https://user-images.githubusercontent.com/50411657/107366988-8785fb00-6abd-11eb-8cc6-6eb38cb9946e.png)

## Como testar?

1. Baixar a branch `refactor/supplyProduct`.
2. Testar o fluxo de cadastro/atualização de produto através da rota `/logged/supply/product/manager`.

2021-02-09 16:07 UTC, guilhermestain commented on src/containers/Supply/Product/ModalRegister/index.js
> +  handleCancel,
colocar em ordem alfabética

2021-02-09 16:08 UTC, guilhermestain commented on src/stories/containers/Supply/Product/Manager/index.js
> +  const [visibleModalUpdate, setVisibleModalUpdate] = useState(false)
colocar em ordem alfabética

2021-02-09 16:08 UTC, guilhermestain commented on src/stories/containers/Supply/Product/Manager/index.js
> +      visibleModalUpdate={visibleModalUpdate}
colocar em ordem alfabética

2021-02-09 16:08 UTC, guilhermestain commented on src/stories/containers/Supply/Product/Manager/index.js
> +  manufacturerList,
colocar em ordem alfabética

2021-02-10 00:01 UTC, novarealponto requested changes

2021-02-10 00:01 UTC, novarealponto commented on src/stories/containers/Supply/Product/Manager/index.js
> +}
```suggestion
const dataSource = new Array(30).fill(null).map((_, index) => ({
    code: key,
    createdAt: moment(date.past()).format('L'),
    exporadic: random.boolean(),
    key,
    manufacturer: company.companyName(),
    manufacturerId: key,
    minimumQuantity: random.number({ max: 20 }),
    product: commerce.productName(),
    unit: ['UNID', 'PÇ', 'CX', 'LT'][random.number({ max: 4 })],
  }))
const manufacturerList = new Array(30).fill(null).map((_, index) => ({
    id: key,
    name: company.companyName(),
  }))

```

2021-02-10 13:10 UTC, alexandrejuk approved these changes

2021-02-11 17:32 UTC, guilhermestain commented on src/containers/Supply/Product/ModalRegister/index.js
> +          </Select>
Trocar Select por um Input.Select para realizarmos buscas no mesmo.

2021-02-11 18:23 UTC, guilhermestain approved these changes

2021-02-11 18:26 UTC, merged