Refactor/supply manufacturer
realponto-project/stock-rp-front pull request #153
Opened 2021-02-09 20:25 UTC by jessiLeandro

## Contexto
neste PR foi criado da página de gerenciamento de fabricante em suprimentos seguindo o mesmo padrão das demais páginas até o momento.

## Checklist
- [ ] Container.
- [ ] Storybook.
- [ ] Page.

## Issues linkadas
- [ ] Resolves #151 

## Screenshots

![image](https://user-images.githubusercontent.com/50411657/107423715-70fe9480-6afb-11eb-9448-f4b8f882c864.png)

![image](https://user-images.githubusercontent.com/50411657/107423730-76f47580-6afb-11eb-829f-756e7475cd56.png)

![image](https://user-images.githubusercontent.com/50411657/107423740-7bb92980-6afb-11eb-95d0-ba6925a4d711.png)

![image](https://user-images.githubusercontent.com/50411657/107423770-85429180-6afb-11eb-9f12-835cf390c88c.png)

## Como testar?

1. Baixar a branch `refactor/supplyManufacturer`.
2. Testar o fluxo de cadastro/atualização de fabricante para suprimentos através da rota `/logged/supply/manufacurer/manager`.

2021-02-10 00:07 UTC, novarealponto requested changes

2021-02-10 00:07 UTC, novarealponto commented on src/pages/Supply/Product/Manager/index.js
> +  }, [getAllSupplyProduct, getAllManufaturer])
temos `getAllManufaturer` aqui, precisamos mesmo dele nos dois effect?

2021-02-10 00:07 UTC, novarealponto commented on src/stories/containers/Supply/Manufacturer/Manager/index.js
> +}
exemplo no outro Pr como devemos fazer esses mocks.

2021-02-10 00:07 UTC, novarealponto commented on src/stories/containers/Supply/Product/Manager/index.js
> +}
exemplo no outro pr de como fazer esses mocks

2021-02-10 12:43 UTC, jessiLeandro commented on src/pages/Supply/Product/Manager/index.js
> +  }, [getAllSupplyProduct, getAllManufaturer])
ops.

2021-02-10 13:10 UTC, alexandrejuk approved these changes

2021-02-11 18:09 UTC, guilhermestain approved these changes

2021-02-11 18:26 UTC, merged