Refactor/login
realponto-project/stock-rp-front pull request #42
Opened 2020-12-03 19:35 UTC by jessiLeandro

https://github.com/realponto-project/stock-rp-front/issues/20

2020-12-03 20:08 UTC, alexandrejuk requested changes

2020-12-03 20:08 UTC, alexandrejuk commented on src/pages/Login/index.js
>        }
```suggestion
    if (has('auth', this.props) && has('token', this.props.auth) {
          return this.setState({ authenticated : true })
      }
```

2020-12-03 20:08 UTC, alexandrejuk commented on src/pages/Login/index.js
> +  hasToken = R.has('token');
Podemos remover esse codigo

2020-12-03 20:08 UTC, alexandrejuk commented on src/pages/Login/LoginRedux/reduce.js
> +  password: '',
vamos colocar as props em ordem alfabeticas

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/style.module.css
> +
remover as linhas em brancos dentro da classe
```suggestion
  border: none;
```

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/style.module.css
> +  position: relative;
remover espaço em branco
```suggestion
  display: flex;
  flex-direction: column;
  align-items: center;
  position: relative;
```

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/style.module.css
> +
remover espaços em branco dentro da classe 
```suggestion
  background-color: white;
```

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/style.module.css
> +  height: 100vh;
colocar as propriedades desse arquivo em ordem alfabetica

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/index.js
> +
remover esse espaço em  branco

2020-12-03 20:08 UTC, alexandrejuk commented on src/containers/Login/index.js
> +
esse espaço está correto

2020-12-03 20:08 UTC, alexandrejuk commented on src/App.js
>    // </MemoryRouter>
remover esse codigo comentado e esse espaço

2020-12-03 20:08 UTC, alexandrejuk commented on src/App.js
remover espaços e codigo comentado

2020-12-03 20:08 UTC, alexandrejuk commented on src/App.js
> +
remover espaço a mais

2020-12-03 20:08 UTC, alexandrejuk commented on src/App.js
remover espaço e codigo comentado e colocar os seus importes depois dos imports de libs do react

2020-12-03 20:55 UTC, alexandrejuk requested changes

2020-12-03 20:55 UTC, alexandrejuk commented on src/pages/Login/index.js
> +
remover esse espaço em branco

2020-12-03 20:55 UTC, alexandrejuk commented on src/pages/Login/index.js
> +
nao vi onde esses caras estao sendo usados maninho

2020-12-04 00:28 UTC, alexandrejuk requested changes

2020-12-04 00:28 UTC, alexandrejuk commented on src/stories/containers/Login/index.js
> +const Template = (args) => <LoginContainar {...args} />
Container está escrito errado

2020-12-04 00:46 UTC, alexandrejuk requested changes

2020-12-04 00:46 UTC, alexandrejuk commented on src/containers/Login/index.js
> +        <img src="../../retina.png" />
Faltou adicionar o alt da image sem ele o console fica imprimindo um alerta 
![image](https://user-images.githubusercontent.com/20932604/101106675-5a920500-35af-11eb-9030-dc3eb33b4721.png)

```suggestion
        <img src="../../retina.png"  alt="company logo"/>
```

2020-12-04 00:46 UTC, alexandrejuk commented on src/containers/Login/index.js
> +          </ItemForm>
Temos que ter somente um name com password se não fica imprimindo alerta no console
![image](https://user-images.githubusercontent.com/20932604/101106821-b9577e80-35af-11eb-9903-ff802abb54a1.png)

```suggestion
          <ItemForm name="actionButton">
            <Button htmlType="submit" type="primary">
              Login
            </Button>
          </ItemForm>
```

2020-12-04 00:46 UTC, alexandrejuk commented on src/containers/Login/index.js
> +      <div className={styles.wrapper}>
não precisamos dessa `div` com o `className={styles.wrapper}` e com esse css temos o mesmo resultado

```css
.container {
  align-items: center;
  background-color: white;
  display: flex;
  flex-direction: column;
  height: 100vh;
  justify-content: center;
  margin: auto;
  overflow: hidden;
  width: 350px;
}

.container h1 {
  color: #0b0550;
  font-size: 32px;
  font-weight: bold;
}

.container img {
  margin-bottom: 20px;
  width: 100%;
}

.container form {
  width: 80%;
}

.container form button {
  background-color: #0b0550;
  border: none;
  position: absolute;
  bottom: 0;
  right: 0;
}

```

2020-12-04 00:47 UTC, alexandrejuk requested changes

2020-12-04 00:47 UTC, alexandrejuk commented on src/stories/containers/Login/index.js
> +import LoginContainar from '../../../containers/Login'
```suggestion
import LoginContainer from '../../../containers/Login'
```

2020-12-04 01:14 UTC, alexandrejuk requested changes

2020-12-04 01:14 UTC, alexandrejuk commented on src/pages/Login/index.js
> +        this.verifyAuth()
Para nao termos essa verificação na mão podemos usar o try catch o código completo para o handle submit ficaria assim
```suggestion
  handleSubmit = async ({ username, password }) => {
    try {
      const { status, data } = await signIn({
        username,
        password,
        typeAccount: {
          stock: true
        }
      });

      if (Number(status) === 401) {
        throw new Error('User UNAUTHORIZED')
      };

      await this.props.onSubmit(data);
      this.verifyAuth();
      this.state.authenticated && this.success();
    } catch (error) {
      this.error();
    }
  };
```

2020-12-04 01:23 UTC, alexandrejuk requested changes

2020-12-04 01:23 UTC, alexandrejuk commented on src/containers/Login/index.js
> +        </Form>
Só a indetação que ficou errada

2020-12-04 12:15 UTC, guilhermestain approved these changes

2020-12-04 12:24 UTC, alexandrejuk requested changes

2020-12-04 12:24 UTC, alexandrejuk commented on src/containers/Login/index.js
> +        <Form name="signIn" onFinish={onSubmit} onFinishFailed={() => {}}>
Se não iremos usar não precisa adicionar `onFinishFailed={() => {}}`

```suggestion
        <Form name="signIn" onFinish={onSubmit}>
```

2020-12-04 14:34 UTC, alexandrejuk approved these changes

2020-12-04 14:59 UTC, merged