Refactor/perfil
realponto-project/stock-rp-front pull request #45
Opened 2020-12-07 20:23 UTC by guilhermestain

## Contexto

## Checklist
- [ ] Itens

## Issues linkadas
- https://github.com/realponto-project/stock-rp-front/issues/38

## Screenshots

### Layout:
[insira o screenshot aqui]

### Preview:
[insira o screenshot aqui]

## Notas de deploy

## Como testar?

**Novos scripts**:

- `script` : detalhes do script

**Novas dependências**:

- `dependency` : detalhes da dependência

**Novas dependências de desenvolvedor**:

- `dependency` : detalhes da dependência

2020-12-08 14:20 UTC, alexandrejuk requested changes

2020-12-08 14:20 UTC, alexandrejuk commented on src/containers/Profile/index.js
> +      </div>
Vamos usar o typography do ant para termos os mesmos padroes de titulo

2020-12-08 14:20 UTC, alexandrejuk commented on src/containers/Profile/index.js
> +          </Button>
Vamos alinhar os items com o Grid do ant

2020-12-08 14:20 UTC, alexandrejuk commented on src/containers/Profile/index.js
> +  editar,
vamos manter o padrão de nome de funções e variaveis em ingles

2020-12-08 14:20 UTC, alexandrejuk commented on src/containers/Profile/style.module.css
> +}
Adiciona um espaço de uma classe para outra e colocar os valores dentro da classe em ordem alfabetica,
e usando o grid do ant é bem provavel que vc não vá precisar de todo esse css

2020-12-08 14:20 UTC, alexandrejuk commented on src/containers/Profile/index.js
> +const PerfilContainer = ({
O nome desse container deveria se `Profile` sem container no final

2020-12-08 14:20 UTC, alexandrejuk commented on src/pages/Profile/index.js
> +    }
Precisamos usar o trycatch dar uma olhada no que estamos fazendo nas outras pages quando fazemos o submit,

2020-12-08 14:20 UTC, alexandrejuk commented on src/pages/Profile/index.js
> +import PerfilContainer from '../../containers/Profile';
Aqui deveria ser ProfileContainer

2020-12-08 14:20 UTC, alexandrejuk commented on src/pages/Profile/index.js
> +const PerfilDash = ({ username, typeAccount }) => {
Aqui deveria ser somente Profile e não ProfileDash

2020-12-08 14:20 UTC, alexandrejuk commented on src/pages/index.js
> +import PerfilDashRoute from "./Profile";
Aqui deveria ser Profile e nao ProfileDash

2020-12-08 14:20 UTC, alexandrejuk commented on src/stories/containers/Profile/index.js
> +import PerfilContainer from '../../../containers/Profile';
Aqui deveria ser ProfileContainer

2020-12-08 14:20 UTC, alexandrejuk commented on src/stories/containers/Profile/index.js
> +  component: PerfilContainer,
Igual o comentario de cima

2020-12-08 14:20 UTC, alexandrejuk commented on src/stories/containers/Profile/index.js
> +    <PerfilContainer
Igual o Comentario de cima

2020-12-08 14:23 UTC, alexandrejuk commented on src/containers/Profile/index.js
> +              <Avatar size={170}>USER</Avatar>
Aqui nesse avatar no lugar de aparece USER poderia aparecer as iniciais do usuario

2020-12-08 15:08 UTC, jessiLeandro commented on src/pages/Profile/index.js
> +  const [editar, setEditar] = useState(false);
corrigir tradução, de editar e setEditar para edit e setEdit, em o arquivo

2020-12-08 15:08 UTC, jessiLeandro commented on src/pages/Profile/index.js
> +
remover linha vazia

2020-12-08 15:08 UTC, jessiLeandro commented on src/pages/Profile/index.js
> +  };
esta função só possui uma linha então não precisa das chaves
```suggestion
  const error = () => message.error('Os dados do usuário não foram atualizados');
```

2020-12-08 15:08 UTC, jessiLeandro commented on src/pages/Profile/index.js
> +  };
esta função só possui uma linha então não precisa das chaves
```suggestion
  const success = () => message.success('Os dados do usuário foram atualizados');
```

2020-12-08 15:08 UTC, jessiLeandro commented on src/pages/Profile/index.js
> +    }
o back-end pode retornar outros status que não sejam 422, por exemplo 401 quando a senha estiver errada, neste caso talvez seja melhor fazer a verificação caso o status for 200.
```suggestion
    if (resposta.status === 200) {
      success();
      setEditar(false);
      form.resetFields();
    } else {
       error();
    }
```

2020-12-08 15:08 UTC, jessiLeandro commented on src/containers/Profile/style.module.css
> +}
corrigir ordem alfabética das propriedades (fazer isto em todas as classes)

```suggestion
.divCard {
  align-items: center;
  height: 95%;
  background-color: white;
  border-radius: 2px;
  display: flex;
  flex-direction: column;
  position: static;
  width: 96%;
}
```

2020-12-10 11:50 UTC, jessiLeandro commented on src/containers/Profile/index.js
> +              </>
Porque usare este fragmento?

2020-12-10 11:50 UTC, jessiLeandro commented on src/containers/Profile/index.js
> +          <>
Porque usar fregment aqui?

2020-12-10 16:29 UTC, jessiLeandro approved these changes

2020-12-10 17:46 UTC, alexandrejuk approved these changes

2020-12-10 17:55 UTC, merged