Refactor/technician
realponto-project/stock-rp-front pull request #46
Opened 2020-12-07 20:39 UTC by jessiLeandro

## Contexto

## Checklist
- [ ] Itens

## Issues linkadas
- [ ] Resolves #

## Screenshots

### Layout:
[insira o screenshot aqui]

### Preview:
[insira o screenshot aqui]

## Notas de deploy

## Como testar?

**Novos scripts**:

- `script` : detalhes do script

**Novas dependências**:

- `dependency` : detalhes da dependência

**Novas dependências de desenvolvedor**:

- `dependency` : detalhes da dependência

2020-12-08 13:02 UTC, alexandrejuk requested changes

2020-12-08 13:02 UTC, alexandrejuk commented on src/utils/index.js
> +  }
Vamos trocar esse switch case por um objeto que a comparação é muito mais rápida
```suggestion
  const rotation = {
     '1':  'Segunda-feira',
     '2':  'Segunda-feira',
     '3':  'Terça-feira',
     '4':  'Terça-feira',
     '5':  'Quarta-feira',
     '6':  'Quarta-feira',
     '7':  'Quinta-feira',
     '8':  'Quinta-feira',
     '9':  'Sexta-feira',
     '0':  'Sexta-feira',
    }
    
    return rotation[lastNumberPlate.toString()]
```

2020-12-08 14:30 UTC, guilhermestain commented on src/containers/Technician/AddTechinician/index.js
> +              />
Tirar espaçamento entre Select e Button +.

2020-12-08 14:33 UTC, guilhermestain commented on src/stories/containers/Technician/AddTechnician/index.js
> +  const saveModalCar = (e) => {
Quando criar novo carro, fechar modal e limpar campos.

2020-12-08 14:39 UTC, guilhermestain commented on src/containers/Technician/AddTechinician/index.js
> +                placeholder="selecione o ano"
```suggestion
                placeholder="Selecione o ano"
```
Corrigir ortografia, SEMPRE COMEÇAR COM LETRAS MAIÚSCULAS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2020-12-08 14:39 UTC, guilhermestain commented on src/containers/Technician/AddTechinician/index.js
> +              <Input placeholder="Digite o nome" />
```suggestion
              <Input placeholder="Digite o nome do técnico" />
```

2020-12-08 14:40 UTC, guilhermestain commented on src/containers/Technician/AddTechinician/index.js
> +          <Input placeholder="Digite o modelo" />
```suggestion
          <Input placeholder="Digite o modelo do carro" />
```

2020-12-08 14:42 UTC, guilhermestain commented on src/pages/Technician/AddTechnician/index.js
> +      messageError('Erro ao cadastras carro')
```suggestion
      messageError('Erro ao cadastrar carro')
```

2020-12-08 14:42 UTC, guilhermestain commented on src/pages/Technician/AddTechnician/index.js
> +      messageError('Erro ao cadastras técnico')
```suggestion
      messageError('Houve um erro ao cadastrar técnico')
```

2020-12-08 16:40 UTC, jessiLeandro commented on src/index.js
> +  <ConfigProvider locale={ptBR}>
isso faz a configuração do idioma, desta forma eu não preciso ficar corrigindo as mesnsagens nas rules de <Form.Item>, não só isso, mas foi mais por essa questão que eu configurei o idioma.

2020-12-08 17:03 UTC, jessiLeandro commented on src/utils/index.js
> +  }
boa, não sabia desta diferença de performance, vou deixar as keys sendo numeros e tirar o  .toString(), pois este metodo faz um match do tipo == e não ===, então não faz tem necessidade de nenhuma converção, neste caso para string, alguns style guides (airbnb e standard) até acusam erro se deixar as keys sendo strings.

2020-12-08 17:08 UTC, jessiLeandro commented on src/containers/Technician/AddTechinician/index.js
> +                placeholder="selecione o ano"
a quantidade de ponto de exclamação em uma exclamação não a intensifica. ;)

2020-12-08 17:14 UTC, jessiLeandro commented on src/containers/Technician/AddTechinician/index.js
> +              />
não entendi

2020-12-09 12:30 UTC, alexandrejuk commented on src/utils/index.js
> +  }
blz pode ser maninho

2020-12-09 13:20 UTC, alexandrejuk commented on src/pages/Technician/AddTechnician/technicianSpec.js
> +  responsibleUser: prop('responsibleUser')
Aqui podemos usar o pathOr 
```suggestion
  responsibleUser: pathOr('modrp', ['responsibleUser'])
```

2020-12-09 13:20 UTC, alexandrejuk commented on src/pages/Technician/AddTechnician/index.js
> +    const technicianFormatted = buildTechnician({...e, responsibleUser: 'modrp'});
remover esse responsibleUser

2020-12-09 13:20 UTC, alexandrejuk commented on src/pages/Technician/AddTechnician/index.js
> +  const saveTechnician = async (e) => {
Nomes dos parametros

2020-12-09 13:20 UTC, alexandrejuk commented on src/pages/Technician/AddTechnician/index.js
> +      const { data ,status } = await newCar(catFormatted);
```suggestion
  const registerNewCar = async (car) => {
    try{
      const { data ,status } = await newCar(buildCar(car));
```

2020-12-09 15:50 UTC, alexandrejuk approved these changes

2020-12-09 19:17 UTC, guilhermestain approved these changes

2020-12-09 20:58 UTC, merged